language: node_js
before_install:
  - "npm install npm -g"
node_js:
  - "5"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
  - "5.9"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
env:
  - TEST_SUITE=unit
script:
  - npm run build
  - npm run $TEST_SUITE